version: "3.8"

services:
  database:
    image: mongo
    volumes:
      - data_portfolio:/data/db
    env_file:
      - ./config/config.env
    ports:
      - 27017:27017
  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./config/config.env
    ports:
      - 3001:3001
    depends_on:
      - database
volumes:
  data_portfolio:
